version: '3.8'

services:
  metro-bundler:
    build: .
    container_name: smd_mobile_metro
    ports:
      - "8081:8081"

    volumes:
      - .:/app

      - /app/node_modules

      - /app/android
      - /app/ios

    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0

    stdin_open: true
    tty: true

    # Lệnh chạy
    command: npm start
