version: "3.8"

services:
  # 1. PostgreSQL Database (Thay thế MySQL)
  postgresdb:
    # Sử dụng image pgvector để hỗ trợ AI sau này, hoặc dùng 'postgres:16' nếu chỉ cần cơ bản
    image: pgvector/pgvector:pg16
    container_name: smd_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: smd_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smd_net

  # 2. Redis Cache
  redis:
    image: redis:latest
    container_name: smd_redis
    ports:
      - "6379:6379"
    networks:
      - smd_net

  # 3. Elasticsearch (Single node for dev)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: smd_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Tắt bảo mật để dev cho dễ
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Giới hạn RAM
    ports:
      - "9200:9200"
    networks:
      - smd_net

volumes:
  postgres_data:

networks:
  smd_net:
    driver: bridge
