version: "3.8"

services:
  # 1. MySQL Database
  mysqldb:
    image: mysql:8.0
    container_name: smd_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smd_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smd_net

  # 2. Redis Cache
  redis:
    image: redis:latest
    container_name: smd_redis
    ports:
      - "6379:6379"
    networks:
      - smd_net

  # 3. Elasticsearch (Single node for dev)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: smd_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Tắt bảo mật để dev cho dễ
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Giới hạn RAM
    ports:
      - "9200:9200"
    networks:
      - smd_net

volumes:
  mysql_data:

networks:
  smd_net:
    driver: bridge
